---

- hosts: directum_local 
  become: true
  vars_files:
    - vars/vars.yml
  
  
  roles:
  - { role: rabbitmq, when: ansible_system == 'Linux' }
  - { role: directum, when: ansible_system == 'Linux' }